CREATE DATABASE T2210M_HOSPITAL

USE T2210M_HOSPITAL

CREATE TABLE DOCTER 
(
		ID INT PRIMARY KEY IDENTITY(1,1),
		NAME VARCHAR(255),
		SPECIALIZE VARCHAR(255) 
)

INSERT INTO DOCTER(NAME,SPECIALIZE)
VALUES
('NGUYEN DUC LAM','SPECISLIST')
INSERT INTO DOCTER(NAME,SPECIALIZE)
VALUES
('LE VAN NAM','SURGERY')
INSERT INTO DOCTER(NAME,SPECIALIZE)
VALUES
('NGUYEN THI HANH','MATERNITY')

SELECT * FROM DOCTER

CREATE TABLE PATIENTS
(
		ID INT PRIMARY KEY IDENTITY(1,1),
		NAME VARCHAR(255),
		IDDOCTER INT NOT NULL REFERENCES DOCTER(ID),
		TELEPHONE INT
)
INSERT INTO PATIENTS(NAME,IDDOCTER,TELEPHONE) VALUES
('HOANG VAN KHANH','1',12345678)
INSERT INTO PATIENTS(NAME,IDDOCTER,TELEPHONE) VALUES
('LE THI NHUNG','2',12312323)
INSERT INTO PATIENTS(NAME,IDDOCTER,TELEPHONE) VALUES
('LE THI HA GIANG ','3',1231241)
SELECT * FROM PATIENTS

CREATE TABLE DIAGNOSIS 
(
	IDDOCTER INT NOT NULL REFERENCES DOCTER(ID),
	IDPATIENTS INT NOT NULL REFERENCES PATIENTS(ID),
	TREATMENTDAY DATETIME,
	DAY DATETIME,
	RESULT VARCHAR(255)
	
)

INSERT INTO DIAGNOSIS (IDDOCTER,IDPATIENTS,DAY,TREATMENTDAY,RESULT) VALUES
('1','2',7,7,'ASDGAHJSDGHA')
SELECT * FROM DOCTER
SELECT * FROM PATIENTS
SELECT * FROM DIAGNOSIS